version: 2
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
 -
  id: spipecat
  main: cmd/spipecat/spipecat.go
  binary: spipecat
  goos:
          - windows
          - linux
          - darwin
  goarch:
          - amd64
          - 386
  ignore:
          - goos: darwin
            goarch: 386
  env:
  - CGO_ENABLED=0
 -
  id: spipec
  main: cmd/spipec/spipec.go
  binary: spipec
  goos:
          - windows
          - linux
          - darwin
  goarch:
          - amd64
          - 386
  ignore:
          - goos: darwin
            goarch: 386
  env:
  - CGO_ENABLED=0
 -
  id: spiped
  main: cmd/spiped/spiped.go
  binary: spiped
  goos:
          - windows
          - linux
          - darwin
  goarch:
          - amd64
          - 386
  ignore:
          - goos: darwin
            goarch: 386
  env:
  - CGO_ENABLED=0
archives:
  -
      format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
